const IMAGES = {
    equipment: require('./image-folder/equipment.webp').default,
    fitTech: require('./image-folder/fittech.webp').default,
    footWear: require('./image-folder/footwear.webp').default,
    womens: require('./image-folder/womens.webp').default,
    mens: require('./image-folder/mens.webp').default,
    battleRopes: require('./image-folder/battleropes.webp').default,
    blueYogaMat: require('./image-folder/blueyogamat.webp').default,
    airDyneBike: require('./image-folder/airdynebike.webp').default,
    jumpRope: require('./image-folder/jumprope.webp').default,
    resistanceBands: require('./image-folder/resistance.webp').default,
    olympicBar: require('./image-folder/olybar.webp').default,
    gymnasticRings: require('./image-folder/gymnastrings.webp').default,
    pullUpBar: require('./image-folder/pullupbar.webp').default,
    exerBall: require('./image-folder/exerball.webp').default,
    iWatch: require('./image-folder/applewatch.webp').default,
    android: require('./image-folder/android.webp').default,
    gShock: require('./image-folder/gshock.webp').default,
    beats: require('./image-folder/beats.webp').default,
    vrHeadSet: require('./image-folder/vrheadset.webp').default,
    lavSet: require('./image-folder/lavender.webp').default,
    greenSet: require('./image-folder/green.webp').default,
    greyCropHoodie: require('./image-folder/greycrop.webp').default,
    multiCol: require('./image-folder/multicol.webp').default,
    gymSharkPants: require('./image-folder/gymshark.webp').default,
    blackFaceMask: require('./image-folder/facemask.webp').default,
    greyThreeQuarter: require('./image-folder/grey3_4t.webp').default,
    pinkNike: require('./image-folder/pinknike.webp').default,
    tennis: require('./image-folder/tennis.webp').default,
    shorts: require('./image-folder/shorts.webp').default,
    driFit: require('./image-folder/drifit.webp').default,
};

export default IMAGES;